# Generated by Django 5.2.1 on 2025-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('units', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('appetizers', 'Appetizers'), ('main course', 'Main Course'), ('dessert', 'Dessert'), ('mostViewed', 'Most Viewed'), ('middleEast', 'Middle Eastern'), ('asia', 'Asian'), ('europe', 'European')], max_length=20)),
                ('description', models.TextField()),
                ('methods', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('isFav', models.BooleanField(default=False)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipes.ingredient')),
            ],
        ),
    ]
